name: SonarCloud Analysis

on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Disable shallow clone for better analysis

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up venv
        run: |
          #!/bin/bash
          set -euxo pipefail

          python3 -m venv env
          source env/bin/activate
          python3 -m pip install --upgrade pip setuptools

          echo "Python path: $(which python3)"
          echo "Python version: $(python3 --version)"
          echo "pip version: $(python3 -m pip --version)"

      - name: Install dependencies
        run: |
          #!/bin/bash
          set -euxo pipefail
          source env/bin/activate

          python3 -m pip install -e .[devel]

      - name: Run tests with coverage
        run: |
          #!/bin/bash
          set -euxo pipefail
          source env/bin/activate

          python3 -m pytest --cov=src/fklearn --cov-report=xml --cov-report=term

      - name: Verify coverage.xml exists
        run: |
          if [ -f coverage.xml ]; then
            echo "✅ coverage.xml generated successfully"
            ls -lh coverage.xml
            echo "Coverage.xml content preview:"
            head -n 20 coverage.xml
          else
            echo "❌ ERROR: coverage.xml not found"
            echo "Files in current directory:"
            ls -la
            exit 1
          fi

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
